export const africaData = [
        "Benin",
    	"Gabon",
        "Burkina Faso",
        "Gambia",
        "Rwanda",
        "Burundi",
        "Ghana",
    	"Sao Tome",
    	"Cameroon", 
        "Guinea",
     	"Senegal",
     	"Cape Verde",
        "Guinea_Bissau",
        "Sierra Leone",
        "Central Africa Republic",
        "Kenya",
    	"South Sudan",
     	"Chad",
        "Liberia",
     	"Tanzania",
    	"Congo",
        "Brazzaville",
        "Malawi",
    	"Togo",
    	"Coted'Ivoire",
        "Mali",
     	"Uganda",
    	"DR Congo",
        "Mozambique",
    	"Zambia",
    	"Equatoria_ Guinea",
        "Niger"
    ];